// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyExcelApp.MvcApp.Data;

#nullable disable

namespace MyExcelApp.MvcApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009202618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MyExcelApp.MvcApp.Models.ExcelFileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHeaderPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowStyle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExcelFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
